//All mutations to be commited on store

//User workflow from application
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const APPLICATION_BY_USER_ID = 'APPLICATION_BY_USER_ID';
export const UPDATE_APPLICATION_STATUS = 'UPDATE_APPLICATION_STATUS';
export const FILTER_APPLICATION_KEYWORD = 'FILTER_APPLICATION_KEYWORD';
export const CHECK_USER_LOGIN_STATUS = 'CHECK_USER_LOGIN_STATUS';
export const ADD_APPLICATION = 'ADD_APPLICATION';
export const ADD_NEW_USER = 'ADD_NEW_USER'
export const RETRIEVE_USER_PROFILE = 'RETRIEVE_USER_PROFILE';
export const FILTER_INSTITUTION_BY_NAME = 'FILTER_INSTITUTION_BY_NAME';
export const FETCH_LOGIN_NAME = 'FETCH_LOGIN_NAME';
export const SUCCESS_LOGIN_MESSAGE = 'SUCCESS_LOGIN_MESSAGE';

//Institution workflow through dashboard 
export const APPLICATION_BY_INSTITUTION_ID = 'APPLICATION_BY_INSTITUTION_ID';
export const CONFIRM_USER_APPLICATION = 'CONFIRM_USER_APPLICATION';
export const RETRIEVE_INSTITUTION_PROFILE = 'RETRIEVE_INSTITUTION_PROFILE';
export const RETRIEVE_PAYMENT_LOG_BY_INSTITUTION_ID = 'RETRIEVE_PAYMENT_LOG_BY_INSTITUTION_ID';

//Flexisaf workflow through dashboard
export const FETCH_ALL_APPLICATIONS = 'FETCH_ALL_APPLICATIONS';
export const FETCH_ALL_INSTITUTION_PROFILE = 'FETCH_ALL_INSTITUTION_PROFILE';
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_ALL_PAYMENT_LOG = 'FETCH_ALL_PAYMENT_LOG';

